### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by PrajwalM2212**
fix typo

### CODE REVIEW

**Comment by chfw** [comment]
will drop python 2.6, which causes this PR to fail

**Comment by PrajwalM2212** [comment]
@chfw How to write a plugin ? The information in docs is scarce. Based on your documentation I have created it like https://github.com/PrajwalM2212/moban/blob/plugin/string_template/string_template_engine.py
From https://github.com/PrajwalM2212/moban/blob/plugin/moban/engine.py, I removed the from jinja2 import Environment, FileSystemLoader and added from string import Template. I just removed all jinja2 specific references and replaced them with corresponding string references. I left all others unaltered as the functionality is same.

Have I done it correctly ? If not, what is the correct way ?

**Comment by chfw** [comment]
https://github.com/moremoban/moban/tree/master/tests/moban-mako provides an example.

and https://lml.readthedocs.io/en/latest/ provides the tutorial.

essentially, a moban plugin is a lml plugin.

**Comment by PrajwalM2212** [comment]
@chfw I read the moban codebase from main.py and realized that all it is doing is parsing the configs and calling https://github.com/moremoban/moban/blob/master/moban/engine.py. The only change is that moban calls different engines based on template type

I read the engine.py and all the work is done by render_to_file , _render_with_finding_template_first and _render_with_finding_data_first methods of the class. Also template = self.jj2_environment.get_template(template_file) and rendered_content = template.render(**data) are the only things that will change from engine to engine.

So I have tried changing those two statements. When I run, it still uses the jinja engine and not stmp engine. 

This is my plugin
https://github.com/PrajwalM2212/moban/tree/plugin/moban-string-temp/moban-string-temp
This is what i run my plugin on 
https://github.com/PrajwalM2212/moban/tree/plugin/docs/level-1-jinja2-cli

When I use --template_type stmp. It gives error stmp. What should I do to run on my plugin and not on jinja2.

**Pull request merged**
