### PR TITLE
Ignore encode error if occurs

### LINKED ISSUE #265: Error in moban 0.4.3
Using moban 0.4.3, we get this error: `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte` in the coala-mobans repo, although this error does not arise with moban 0.3.3.

CI log:
 - moban 0.3.3: https://gitlab.com/ayan-b/mobans/-/jobs/199587253
 - moban 0.4.3: https://gitlab.com/ayan-b/mobans/-/jobs/199585396

### PR DESCRIPTION
**Pull request by ayan-b**
Closes #265

Before raising the PR, here is a check list:

1) have you written unit tests for your code changes?
2) have you run "make format"?
3) are you requesting to "dev"?
4) have you updated the change log?
5) do you think that you can understand your changes after 6 month?
   5.1) can someone else understand your changes without your explanation?
6) are you pround of your code changes?
   6.1) do you have the feeling of achievement?
7) please add your name and github link to contributors.rst in alphabetical order.

### CODE REVIEW

**Comment by ayan-b** [comment]
Job passes: https://gitlab.com/ayan-b/mobans/-/jobs/203626328

**Comment by chfw** [comment]
I see now. It is because of replacing function, we need to decide the content, for copy engine, it is not needed. So it means current architecture is at fault, meaning it is not general enough to accommodate template and copy engine.

**Comment by ayan-b** [comment]
What about this https://github.com/moremoban/moban/issues/265#issuecomment-487046787 ?

**Comment by chfw** [comment]
That sounds good but have to fit them in the template interface

**Comment by chfw** [comment]
By the way, without reading the content, hashstore may not function well. So os copy will not work well.

In general, the same content will not be templates/copied twice.

**Comment by ayan-b** [comment]
@chfw please review.

**Comment by chfw** [comment]
the test case should trigger 'copy engine' end-to-end, meaning: a file is copied to output file path. At the moment, it does not do it.

**Comment by chfw** [comment]
I was on holiday. I should be able to help next week.

**Comment by ayan-b** [comment]
Maybe we can pass a `mobanfile` in the `handle_mobanfile` function and check the output?

**Comment by chfw** [comment]
no hurry!

**Comment by ayan-b** [comment]
> the test case should trigger 'copy engine' end-to-end, meaning: a file is copied to output file path. At the moment, it does not do it.

Can you please help me here?

**Comment by chfw** [comment]
let me find some time. I was thinking of end2end test like what we did for all documentations.

**Comment by chfw** [comment]
let me find some time. I was thinking of end2end test like what we did for all documentations.

like this: https://github.com/moremoban/moban/tree/dev/docs/level-15-copy-templates-as-target

**Comment by chfw** [comment]
could you please try merge it with https://github.com/moremoban/moban/tree/regression-test-coping-binary-file?

**Pull request merged**
