### PR TITLE
release 0.5.0

### PR DESCRIPTION
**Pull request by chfw**
see changelog for more details.

### CODE REVIEW

**Comment by jayvdb** [comment]
I dont understand the benefit of the commit `" hammer minimize the changes in setup.py "` .  The changes already happened in earlier commits.  Adding another commit to change them back only makes the commit history more complicated.

And it breaks the moban job, which is designed to stop people doing little "local" hacks like that. :P

**Comment by chfw** [comment]
Will need remove moban stage.

The minimization would reveal less change in dev to master diff. And the hammer tool is black, which won’t take a minute.

**Comment by jayvdb** [comment]
I dont understand.  If you remove your commit, the build will pass, and the release can be done.

Other problems can then be created as issues and discussed/prioritised normally.

**Comment by chfw** [comment]
@jayvdb , I am sorry to be a numpty. I did not realize the function of moban stage.

**Pull request merged**
