### PR TITLE
Install external mobans through requires

### PR DESCRIPTION
**Pull request by chfw**
#35 #86 #87 #88

 newsly instroduced "requires":
```
requires:
   - pypi-mobans-pkg
configuration:
  template_dir:
    - "pypi-mobans-pkg:templates" <-- this is how it is used
    - local
  configuration: config.yml
targets:
  - mytravis.yml: travis.yml.jj2
  - test.txt: demo.txt.jj2
```

### CODE REVIEW

**Comment by jayvdb** [comment]
Will `requires` support git URLs?

while releasing a packaging is nice, it isnt dynamic enough.

we need developers to set up a branch of our mobans repo, and be able to use that moban branch as their upstream while developing in other repos, using that un-merged moban enhancement.  Once they have it all working well, we merge the moban enhancement and then they re-push their PR in other repos to use the master of the moban repo.

**Comment by chfw** [comment]
Yes, It will support git urls. I will think about its require syntax and the checkout location.

**Comment by chfw** [comment]
With pkg, it is possible to have versions. With git repo, it then,as you said allow dynamic synchronization.

**Comment by chfw** [comment]
Ok. Please approve this PR and I will submit another one for git

**Pull request merged**
