### PR TITLE
Fix double stdout fixes #393

### LINKED ISSUE #393: Rendered content output to stdout twice
This only happens when the template is coming from a file. For instance this works as intended:

```
--> HELLO="hello there" moban "Here is my greeting: {{HELLO}}"
Here is my greeting: hello there
```

But if you are getting it from a file for example `template.txt.jj2`:

```
{{HELLO}}
```

where `data.yaml` is:

```
HELLO: "hello there"
```

These result:

```
--> moban -c data.yaml -t example.txt.jj2
hello there
hello there

--> HELLO="hello there" moban -t example.txt.jj2
hello there
hello there
```

I have a fix, just prepping the PR.

### PR DESCRIPTION
**Pull request by salotz**
Before raising the PR, here is a check list:

- [ ] have you written unit tests for your code changes?
- [X] have you updated the change log?
- [X] can someone else understand your changes without your explanation?
- [X] are you proud of your code changes?
- [X] please add your name and github link to contributors.rst in alphabetical order.

Any tips on how to write a test for it?

### CODE REVIEW

**Comment by chfw** [comment]
Your contribution is welcome!

1) would you like to run 'make format' on the source code?
2) would you like to write a unit test for it? here is the unit test I wrote for this feature: https://github.com/moremoban/moban/blob/dev/tests/integration_tests/test_command_line_options.py#L567

**Comment by salotz** [comment]
Sorry meant to circle back around to this when I had the time.

**Comment by chfw** [comment]
That's alright. It was a show stopper hence I changed my mind to close it up.

**Comment by chfw** [comment]
I have also removed v0.7.9 from pypi.

**Pull request merged**
